name: Build iOS

on: [push]

jobs:
  build:
    name: install dependencies
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
